language: objective-c

before_install:
  - cd Example

install:
  - pod install

xcode_workspace: Example/Example.xcworkspace
xcode_scheme: OpinionatedC

cache:
  - bundler
  - cocoapods

after_success:
  - slather
