language: objective-c

before_install:
  - gem install slather --no-ri --no-rdoc

podfile: Example/Podfile

xcode_workspace: Example/Example.xcworkspace
xcode_scheme: OpinionatedC

after_success:
  - slather
