language: objective-c

podfile: Example/Podfile

before_install:
  - cd Example

install:
  - gem install xcpretty --no-ri --no-rdoc

script:
  - xcodebuild -workspace Example.xcworkspace -scheme OpinionatedC test | xcpretty -c && exit ${PIPESTATUS[0]}
